### ISSUE TITLE
chemprop_predict gives libcupti.so errors

### ISSUE THREAD

**Issue by Evert-Homan** [swansonk14/SyntheMol#11]
Hi, I have a number of precomputed chemprop models and wanted to give it a shot with one of them, trying to generate new ligands. However I am getting error messages reg. missing library (libcupti.so ?) when predicting the activities for the building blocks. I followed the installation instructions for a local installation and invoked pip install -r requirements.txt. FYI, I have CUDA 12.2 installed (not 11.7).

Please advise. Thank you, Evert

chemprop_predict \
    --test_path "$(python -c 'import synthemol; print(str(synthemol.constants.BUILDING_BLOCKS_PATH))')" \
    --preds_path models/MTH1_pIC50_bb.csv \
    --checkpoint_dir ~/Data/CompChem/Python/chemprop_v1/Models/MTH1_pIC50/MTH1_pIC50_cv10
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/evehom/Data/CompChem/Python/SyntheMol/synthemol/__init__.py", line 3, in <module>
    import synthemol.generate
  File "/home/evehom/Data/CompChem/Python/SyntheMol/synthemol/generate/__init__.py", line 2, in <module>
    from synthemol.generate.generate import generate
  File "/home/evehom/Data/CompChem/Python/SyntheMol/synthemol/generate/generate.py", line 25, in <module>
    from synthemol.generate.utils import create_model_scoring_fn, save_generated_molecules
  File "/home/evehom/Data/CompChem/Python/SyntheMol/synthemol/generate/utils.py", line 8, in <module>
    import torch
  File "/home/evehom/miniforge3/envs/synthemol/lib/python3.10/site-packages/torch/__init__.py", line 229, in <module>
    from torch._C import *  # noqa: F403
ImportError: libcupti.so.11.7: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/evehom/miniforge3/envs/synthemol/bin/chemprop_predict", line 5, in <module>
    from chemprop.train import chemprop_predict
  File "/home/evehom/miniforge3/envs/synthemol/lib/python3.10/site-packages/chemprop/__init__.py", line 1, in <module>
    import chemprop.data
  File "/home/evehom/miniforge3/envs/synthemol/lib/python3.10/site-packages/chemprop/data/__init__.py", line 1, in <module>
    from .data import cache_graph, cache_mol, MoleculeDatapoint, MoleculeDataset, MoleculeDataLoader, \
  File "/home/evehom/miniforge3/envs/synthemol/lib/python3.10/site-packages/chemprop/data/data.py", line 7, in <module>
    from torch.utils.data import DataLoader, Dataset, Sampler
  File "/home/evehom/miniforge3/envs/synthemol/lib/python3.10/site-packages/torch/__init__.py", line 229, in <module>
    from torch._C import *  # noqa: F403
ImportError: libcupti.so.11.7: cannot open shared object file: No such file or directory

**Comment by Evert-Homan** [comment]
Hi again,

I reinstalled PyTorch in the environment, which has resolved the libcupti.so error. However I am getting different errors now, but these may be related to the flags that were set when training the chemprop models. I will put a separate question in for this.

Thanks/Evert

**Comment by swansonk14** [comment]
Hi @Evert-Homan,

Thanks for raising the issue and posting the update! I'll close this issue since it seems like you found a fix for the libcupti.so errors, but please feel free to reopen the issue or open a new one if you're still having problems.

Best,
Kyle
